services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reddit_scraper_bot
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: ["python", "python_files/main.py"]